emojis = [ 
("😀", "SMILING FACE"),
("😃", "SMILING FACE WITH BIG EYES"),
("😄", "GRINNING FACE WITH SMILING EYES"),
("😁", "BEAMING FACE WITH SMILING EYES"),
("😆", "SMILING SQUINTING FACE"),
("😅", "SMILING FACE WITH SWEAT"),
("😂", "FACE WITH TEARS OF JOY"),
("🤣", "ROLLING ON THE FLOOR LAUGHING"),
("😊", "SMILING FACE WITH SMILING EYES"),
("🙂", "SLIGHTLY SMILING FACE"),
("🙃", "UPSIDE-DOWN FACE"),
("😉", "WINKING FACE"),
("😌", "RELIEVED FACE"),
("😍", "HEART EYES"),
("😘", "FACE BLOWING A KISS"),
("😗", "KISSING FACE"),
("😙", "KISSING FACE WITH SMILING EYES"),
("😚", "KISSING FACE WITH CLOSED EYES"),
("😋", "FACE SAVORING FOOD"),
("😛", "FACE WITH TONGUE"),
("😜", "WINKING FACE WITH TONGUE"),
("😝", "SQUINTING FACE WITH TONGUE"),
("🤑", "MONEY-MOUTH FACE"),
("🤗", "HUGGING FACE"),
("😎", "SMILING FACE WITH SUNGLASSES"),
("😏", "SMIRKING FACE"),
("😒", "UNAMUSED FACE"),
("😞", "DISAPPOINTED FACE"),
("😔", "PENSIVE FACE"),
("😟", "WORRIED FACE"),
("😕", "CONFUSED FACE"),
("🙁", "SLIGHTLY FROWNING FACE"),
("☹️", "FROWNING FACE"),
("😣", "PERSEVERING FACE"),
("😖", "CONFOUNDED FACE"),
("😫", "TIRED FACE"),
("😩", "CRYING FACE"),
("😤", "FACE WITH STEAM FROM NOSE"),
("😠", "ANGRY FACE"),
("😡", "POUTING FACE"),
("😶", "FACE WITHOUT MOUTH"),
("😐", "NEUTRAL FACE"),
("😑", "EXPRESSIONLESS FACE"),
("😬", "GRIMACING FACE"),
("😮", "FACE WITH OPEN MOUTH"),
("😯", "HUSHED FACE"),
("😰", "FACE WITH OPEN MOUTH AND COLD SWEAT"),
("😨", "FEARFUL FACE"),
("😧", "ANGUISHED FACE"),
("😲", "ASTONISHED FACE"),
("😳", "FLUSHED FACE"),
("😦", "FROWNING FACE WITH OPEN MOUTH"),
("😵", "DIZZY FACE"),
("😪", "SLEEPY FACE"),
("😴", "SLEEPING FACE"),
("😷", "FACE WITH MEDICAL MASK"),
("🤒", "FACE WITH THERMOMETER"),
("🤕", "FACE WITH HEAD-BANDAGE"),
("🤢", "NAUSEATED FACE"),
("🤮", "FACE VOMITING"),
("🤧", "SNEEZING FACE"),
("😇", "SMILING FACE WITH HALO"),
("🤠", "COWBOY HAT FACE"),
("🤡", "CLOWN FACE"),
("🤥", "LYING FACE"),
("🤫", "SHUSHING FACE"),
("🤭", "FACE WITH HAND OVER MOUTH"),
("🧐", "FACE WITH MONOCLE"),
("🤓", "NERD FACE"),
("😈", "SMILING FACE WITH HORNS"),
("👿", "ANGRY FACE WITH HORNS"),
("👹", "OGRE"),
("👺", "GOBLIN"),
("💀", "SKULL"),
("👻", "GHOST"),
("👽", "ALIEN"),
("👾", "ALIEN MONSTER"),
("🤖", "ROBOT FACE"),
("💩", "PILE OF POO"),
("😺", "GRINNING CAT FACE"),
("😸", "GRINNING CAT FACE WITH SMILING EYES"),
("😹", "CAT FACE WITH TEARS OF JOY"),
("😻", "SMILING CAT FACE WITH HEART-EYES"),
("😼", "CAT FACE WITH WRY SMILE"),
("😽", "KISSING CAT FACE"),
("🙀", "WEARY CAT FACE"),
("😿", "CRYING CAT FACE"),
("😾", "POUTING CAT FACE"),
("👐", "OPEN HANDS"),
("🙌", "RAISING HANDS"),
("👏", "CLAPPING HANDS"),
("🤝", "HANDSHAKE"),
("👊", "ONCOMING FIST"),
("✊", "RAISED FIST"),
("🤛", "FIST BUMP"),
("🤜", "FIST LEFT"),
("✌️", "VICTORY HAND"),
("👌", "OK HAND"),
("👍", "THUMBS UP"),
("👎", "THUMBS DOWN"),
("👋", "WAVING HAND"),
("🤚", "RAISED BACK OF HAND"),
("🖐️", "HAND WITH FINGERS SPLAYED"),
("✋", "RAISED HAND"),
("🤏", "PINCHING HAND"),
("🤞", "CROSSED FINGERS"),
("🤟", "LOVE-YOU GESTURE"),
("🤘", "SIGN OF THE HORNS"),
("🤙", "CALL ME HAND"),
("👈", "BACKHAND INDEX POINTING LEFT"),
("👉", "BACKHAND INDEX POINTING RIGHT"),
("👆", "BACKHAND INDEX POINTING UP"),
("🖕", "REVERSED HAND WITH MIDDLE FINGER EXTENDED"),
("👇", "BACKHAND INDEX POINTING DOWN"),
("☝️", "INDEX POINTING UP"),
("👁️", "EYE"),
("👁️‍🗨️", "EYE IN SPEECH BUBBLE"),
("👂", "EAR"),
("👃", "NOSE"),
("👄", "MOUTH"),
("👅", "TONGUE"),
("💋", "KISS MARK"),
("👓", "GLASSES"),
("🕶️", "DARK SUNGLASSES"),
("👟", "RUNNING SHOE"),
("👞", "MEN'S SHOE"),
("👠", "HIGH-HEELED SHOE"),
("👡", "WOMAN'S SANDAL"),
("🥿", "FLAT SHOE"),
("👢", "WOMAN'S BOOTS"),
("👕", "T-SHIRT"),
("👔", "NECKTIE"),
("👚", "WOMAN'S CLOTHES"),
("👗", "DRESS"),
("🧣", "SCARF"),
("🧤", "GLOVES"),
("🧥", "COAT"),
("🧦", "SOCKS"),
("🧢", "BILLED CAP"),
("🎩", "TOP HAT"),
("👑", "CROWN"),
("👒", "WOMAN'S HAT"),
("🧚‍♂️", "MAN FAIRY"),
("🧚‍♀️", "WOMAN FAIRY"),
("🧝‍♂️", "MAN ELF"),
("🧝‍♀️", "WOMAN ELF"),
("🧛‍♂️", "MAN VAMPIRE"),
("🧛‍♀️", "WOMAN VAMPIRE"),
("🧜‍♂️", "MAN MERMAID"),
("🧜‍♀️", "WOMAN MERMAID"),
("🧞‍♂️", "MAN GENIE"),
("🧞‍♀️", "WOMAN GENIE"),
("🧟‍♂️", "MAN ZOMBIE"),
("🧟‍♀️", "WOMAN ZOMBIE"),
("🎅", "SANTA CLAUS"),
("🤶", "MRS. CLAUS"),
("🦸‍♂️", "MAN SUPERHERO"),
("🦸‍♀️", "WOMAN SUPERHERO"),
("🦹‍♂️", "MAN SUPERVILLAIN"),
("🦹‍♀️", "WOMAN SUPERVILLAIN"),
("🧙‍♂️", "MAN WIZARD"),
("🧙‍♀️", "WOMAN WIZARD"),
("🦝", "RACCOON"),
("🦙", "LLAMA"),
("🦛", "HIPPOPOTAMUS"),
("🦘", "KANGAROO"),
("🦒", "GIRAFFE"),
("🦔", "HEDGEHOG"),
("🦕", "SAUROPOD"),
("🦖", "T-REX"),
("🦗", "CRICKET"),
("🦟", "MOSQUITO"),
("🦂", "SCORPION"),
("🦠", "MICROBE"),
("🧼", "SOAP"),
("🧽", "SPONGE"),
("🧴", "LOTION BOTTLE"),
("🧻", "ROLL OF PAPER"),
("🧷", "SAFETY PIN"),
("🧹", "BROOM"),
("🧺", "BASKET"),
("🏀", "BASKETBALL"),
("🏈", "AMERICAN FOOTBALL"),
("⚾", "BASEBALL"),
("🥎", "SOFTBALL"),
("🎾", "TENNIS"),
("🏐", "VOLLEYBALL"),
("🏉", "RUGBY FOOTBALL"),
("🎱", "BILLIARDS"),
("🏓", "PING PONG"),
("🏸", "BADMINTON"),
("🥏", "FLYING DISC"),
("🪀", "YO-YO"),
("🥍", "LACROSSE"),
("🏒", "ICE HOCKEY"),
("🏑", "FIELD HOCKEY"),
("🥅", "GOAL NET"),
("🏏", "CRICKET GAME"),
("⛳", "FLAG IN HOLE"),
("🪁", "KITE"),
("🏹", "BOW AND ARROW"),
("🎣", "FISHING POLE"),
("🤿", "DIVING MASK"),
("🥊", "BOXING GLOVE"),
("🥋", "MARTIAL ARTS UNIFORM"),
("🎽", "RUNNING SHIRT"),
("🛹", "SKATEBOARD"),
("🛷", "SLED"),
("🪂", "PARACHUTE"),
("🪐", "RINGED PLANET"),
("🌍", "EARTH GLOBE EUROPE-AFRICA"),
("🌎", "EARTH GLOBE AMERICAS"),
("🌏", "EARTH GLOBE ASIA-AUSTRALIA"),
("🌐", "GLOBE WITH MERIDIANS"),
("🌑", "NEW MOON"),
("🌒", "WAXING CRESCENT MOON"),
("🌓", "FIRST QUARTER MOON"),
("🌔", "WAXING GIBBOUS MOON"),
("🌕", "FULL MOON"),
("🌖", "WANING GIBBOUS MOON"),
("🌗", "LAST QUARTER MOON"),
("🌘", "WANING CRESCENT MOON"),
("🌙", "CRESCENT MOON"),
("🌚", "NEW MOON FACE"),
("🌛", "FIRST QUARTER MOON FACE"),
("🌜", "LAST QUARTER MOON FACE"),
("🌡️", "THERMOMETER"),
("🌦️", "SUN BEHIND RAIN CLOUD"),
("🌧️", "CLOUD WITH RAIN"),
("🌨️", "CLOUD WITH SNOW"),
("🌩️", "CLOUD WITH LIGHTNING"),
("🌪️", "TORNADO"),
("🌫️", "FOG"),
("🌬️", "WIND FACE"),
("🌀", "CYCLONE"),
("🌈", "RAINBOW"),
("🌂", "CLOSED UMBRELLA"),
("☂️", "UMBRELLA"),
("☔", "UMBRELLA WITH RAIN DROPS"),
("⛱️", "UMBRELLA ON GROUND"),
("⚡", "HIGH VOLTAGE"),
("❄️", "SNOWFLAKE"),
("☃️", "SNOWMAN"),
("⛄", "SNOWMAN WITHOUT SNOW"),
("☄️", "COMET"),
("🔥", "FIRE"),
("💧", "DROPLET"),
("🌊", "WATER WAVE"),
("🎃", "JACK-O-LANTERN"),
("🎄", "CHRISTMAS TREE"),
("🎆", "FIREWORKS"),
("🎇", "SPARKLER"),
("🧨", "FIRECRACKER"),
("✨", "SPARKLES"),
("🎈", "BALLOON"),
("🎉", "PARTY POPPER"),
("🎊", "CONFETTI BALL"),
("🎋", "TANABATA TREE"),
("🎍", "PINE DECORATION"),
("🎎", "JAPANESE DOLLS"),
("🎏", "CARP STREAMER"),
("🎐", "WIND CHIME"),
("🎑", "MOON VIEWING CEREMONY"),
("🎒", "SCHOOL SATCHEL"),
("🎓", "GRADUATION CAP"),
("🎟️", "ADMISSION TICKETS"),
("🎫", "TICKET"),
("🎖️", "MILITARY MEDAL"),
("🏆", "TROPHY"),
("🏅", "SPORTS MEDAL"),
("🥇", "FIRST PLACE MEDAL"),
("🥈", "SECOND PLACE MEDAL"),
("🥉", "THIRD PLACE MEDAL"),
("⚽", "SOCCER BALL"),
("❤️", "Red Heart"),
("🧡", "Orange Heart"),
("💛", "Yellow Heart"),
("💚", "Green Heart"),
("💙", "Blue Heart"),
("💜", "Purple Heart"),
("🖤", "Black Heart"),
("🤍", "White Heart"),
("💔", "Broken Heart"),
("❣️", "Heart Exclamation"),
("💕", "Two Hearts"),
("💞", "Revolving Hearts"),
("💓", "Beating Heart"),
("💗", "Growing Heart"),
("💖", "Sparkling Heart"),
("💘", "Heart with Arrow"),
("💝", "Heart with Ribbon"),
("💟", "Heart Decoration"),
("🇦🇫", "Afghanistan Flag"),
("🇦🇽", "Åland Islands Flag"),
("🇦🇱", "Albania Flag"),
("🇩🇿", "Algeria Flag"),
("🇦🇸", "American Samoa Flag"),
("🇦🇩", "Andorra Flag"),
("🇦🇴", "Angola Flag"),
("🇦🇮", "Anguilla Flag"),
("🇦🇶", "Antarctica Flag"),
("🇦🇬", "Antigua & Barbuda Flag"),
("🇦🇷", "Argentina Flag"),
("🇦🇲", "Armenia Flag"),
("🇦🇼", "Aruba Flag"),
("🇦🇺", "Australia Flag"),
("🇦🇹", "Austria Flag"),
("🇦🇿", "Azerbaijan Flag"),
("🇧🇸", "Bahamas Flag"),
("🇧🇭", "Bahrain Flag"),
("🇧🇩", "Bangladesh Flag"),
("🇧🇧", "Barbados Flag"),
("🇧🇾", "Belarus Flag"),
("🇧🇪", "Belgium Flag"),
("🇧🇿", "Belize Flag"),
("🇧🇯", "Benin Flag"),
("🇧🇲", "Bermuda Flag"),
("🇧🇹", "Bhutan Flag"),
("🇧🇴", "Bolivia Flag"),
("🇧🇦", "Bosnia & Herzegovina Flag"),
("🇧🇼", "Botswana Flag"),
("🇧🇻", "Bouvet Island Flag"),
("🇧🇷", "Brazil Flag"),
("🇮🇴", "British Indian Ocean Territory Flag"),
("🇻🇬", "British Virgin Islands Flag"),
("🇧🇳", "Brunei Flag"),
("🇧🇬", "Bulgaria Flag"),
("🇧🇫", "Burkina Faso Flag"),
("🇧🇮", "Burundi Flag"),
("🇰🇭", "Cambodia Flag"),
("🇨🇲", "Cameroon Flag"),
("🇨🇦", "Canada Flag"),
("🇨🇻", "Cape Verde Flag"),
("🇧🇶", "Caribbean Netherlands Flag"),
("🇰🇾", "Cayman Islands Flag"),
("🇨🇫", "Central African Republic Flag"),
("🇹🇩", "Chad Flag"),
("🇨🇱", "Chile Flag"),
("🇨🇳", "China Flag"),
("🇨🇽", "Christmas Island Flag"),
("🇨🇨", "Cocos (Keeling) Islands Flag"),
("🇨🇴", "Colombia Flag"),
("🇰🇲", "Comoros Flag"),
("🇨🇬", "Congo - Brazzaville Flag"),
("🇨🇩", "Congo - Kinshasa Flag"),
("🇨🇰", "Cook Islands Flag"),
("🇨🇷", "Costa Rica Flag"),
("🇨🇮", "Côte d’Ivoire Flag"),
("🇭🇷", "Croatia Flag"),
("🇨🇺", "Cuba Flag"),
("🇨🇼", "Curaçao Flag"),
("🇨🇾", "Cyprus Flag"),
("🇨🇿", "Czechia Flag"),
("🇩🇰", "Denmark Flag"),
("🇩🇯", "Djibouti Flag"),
("🇩🇲", "Dominica Flag"),
("🇩🇴", "Dominican Republic Flag"),
("🇪🇨", "Ecuador Flag"),
("🇪🇬", "Egypt Flag"),
("🇸🇻", "El Salvador Flag"),
("🇬🇶", "Equatorial Guinea Flag"),
("🇪🇷", "Eritrea Flag"),
("🇪🇪", "Estonia Flag"),
("🇸🇿", "Eswatini Flag"),
("🇪🇹", "Ethiopia Flag"),
("🇫🇰", "Falkland Islands (Islas Malvinas) Flag"),
("🇫🇴", "Faroe Islands Flag"),
("🇫🇯", "Fiji Flag"),
("🇫🇮", "Finland Flag"),
("🇫🇷", "France Flag"),
("🇬🇫", "French Guiana Flag"),
("🇵🇫", "French Polynesia Flag"),
("🇹🇫", "French Southern Territories Flag"),
("🇬🇦", "Gabon Flag"),
("🇬🇲", "Gambia Flag"),
("🇬🇪", "Georgia Flag"),
("🇩🇪", "Germany Flag"),
("🇬🇭", "Ghana Flag"),
("🇬🇮", "Gibraltar Flag"),
("🇬🇷", "Greece Flag"),
("🇬🇱", "Greenland Flag"),
("🇬🇩", "Grenada Flag"),
("🇬🇵", "Guadeloupe Flag"),
("🇬🇺", "Guam Flag"),
("🇬🇹", "Guatemala Flag"),
("🇬🇬", "Guernsey Flag"),
("🇬🇳", "Guinea Flag"),
("🇬🇼", "Guinea-Bissau Flag"),
("🇬🇾", "Guyana Flag"),
("🇭🇹", "Haiti Flag"),
("🇭🇳", "Honduras Flag"),
("🇭🇰", "Hong Kong SAR China Flag"),
("🇭🇺", "Hungary Flag"),
("🇮🇸", "Iceland Flag"),
("🇮🇳", "India Flag"),
("🇮🇩", "Indonesia Flag"),
("🇮🇷", "Iran Flag"),
("🇮🇶", "Iraq Flag"),
("🇮🇪", "Ireland Flag"),
("🇮🇲", "Isle of Man Flag"),
("🇮🇱", "Israel Flag"),
("🇮🇹", "Italy Flag"),
("🇯🇲", "Jamaica Flag"),
("🇯🇵", "Japan Flag"),
("🇯🇪", "Jersey Flag"),
("🇯🇴", "Jordan Flag"),
("🇰🇿", "Kazakhstan Flag"),
("🇰🇪", "Kenya Flag"),
("🇰🇮", "Kiribati Flag"),
("🇽🇰", "Kosovo Flag"),
("🇰🇼", "Kuwait Flag"),
("🇰🇬", "Kyrgyzstan Flag"),
("🇱🇦", "Laos Flag"),
("🇱🇻", "Latvia Flag"),
("🇱🇧", "Lebanon Flag"),
("🇱🇸", "Lesotho Flag"),
("🇱🇷", "Liberia Flag"),
("🇱🇾", "Libya Flag"),
("🇱🇮", "Liechtenstein Flag"),
("🇱🇹", "Lithuania Flag"),
("🇱🇺", "Luxembourg Flag"),
("🇲🇴", "Macao SAR China Flag"),
("🇲🇰", "North Macedonia Flag"),
("🇲🇬", "Madagascar Flag"),
("🇲🇼", "Malawi Flag"),
("🇲🇾", "Malaysia Flag"),
("🇲🇻", "Maldives Flag"),
("🇲🇱", "Mali Flag"),
("🇲🇹", "Malta Flag"),
("🇲🇭", "Marshall Islands Flag"),
("🇲🇶", "Martinique Flag"),
("🇲🇷", "Mauritania Flag"),
("🇲🇺", "Mauritius Flag"),
("🇾🇹", "Mayotte Flag"),
("🇲🇽", "Mexico Flag"),
("🇫🇲", "Micronesia Flag"),
("🇲🇩", "Moldova Flag"),
("🇲🇨", "Monaco Flag"),
("🇲🇳", "Mongolia Flag"),
("🇲🇪", "Montenegro Flag"),
("🇲🇸", "Montserrat Flag"),
("🇲🇦", "Morocco Flag"),
("🇲🇿", "Mozambique Flag"),
("🇲🇲", "Myanmar (Burma) Flag"),
("🇳🇦", "Namibia Flag"),
("🇳🇷", "Nauru Flag"),
("🇳🇵", "Nepal Flag"),
("🇳🇱", "Netherlands Flag"),
("🇳🇨", "New Caledonia Flag"),
("🇳🇿", "New Zealand Flag"),
("🇳🇮", "Nicaragua Flag"),
("🇳🇪", "Niger Flag"),
("🇳🇬", "Nigeria Flag"),
("🇳🇺", "Niue Flag"),
("🇳🇫", "Norfolk Island Flag"),
("🇰🇵", "North Korea Flag"),
("🇲🇵", "Northern Mariana Islands Flag"),
("🇳🇴", "Norway Flag"),
("🇴🇲", "Oman Flag"),
("🇵🇰", "Pakistan Flag"),
("🇵🇼", "Palau Flag"),
("🇵🇸", "Palestinian Territories Flag"),
("🇵🇦", "Panama Flag"),
("🇵🇬", "Papua New Guinea Flag"),
("🇵🇾", "Paraguay Flag"),
("🇵🇪", "Peru Flag"),
("🇵🇭", "Philippines Flag"),
("🇵🇳", "Pitcairn Islands Flag"),
("🇵🇱", "Poland Flag"),
("🇵🇹", "Portugal Flag"),
("🇵🇷", "Puerto Rico Flag"),
("🇶🇦", "Qatar Flag"),
("🇷🇴", "Romania Flag"),
("🇷🇺", "Russia Flag"),
("🇷🇼", "Rwanda Flag"),
("🇷🇪", "Réunion Flag"),
("🇼🇸", "Samoa Flag"),
("🇸🇲", "San Marino Flag"),
("🇸🇦", "Saudi Arabia Flag"),
("🇸🇳", "Senegal Flag"),
("🇷🇸", "Serbia Flag"),
("🇸🇨", "Seychelles Flag"),
("🇸🇱", "Sierra Leone Flag"),
("🇸🇬", "Singapore Flag"),
("🇸🇽", "Sint Maarten Flag"),
("🇸🇰", "Slovakia Flag"),
("🇸🇮", "Slovenia Flag"),
("🇸🇧", "Solomon Islands Flag"),
("🇸🇴", "Somalia Flag"),
("🇿🇦", "South Africa Flag"),
("🇬🇸", "South Georgia & South Sandwich Islands Flag"),
("🇰🇷", "South Korea Flag"),
("🇸🇸", "South Sudan Flag"),
("🇪🇸", "Spain Flag"),
("🇱🇰", "Sri Lanka Flag"),
("🇧🇱", "St. Barthélemy Flag"),
("🇸🇭", "St. Helena Flag"),
("🇰🇳", "St. Kitts & Nevis Flag"),
("🇱🇨", "St. Lucia Flag"),
("🇲🇫", "St. Martin Flag"),
("🇵🇲", "St. Pierre & Miquelon Flag"),
("🇻🇨", "St. Vincent & Grenadines Flag"),
("🇸🇩", "Sudan Flag"),
("🇸🇷", "Suriname Flag"),
("🇸🇯", "Svalbard & Jan Mayen Flag"),
("🇸🇪", "Sweden Flag"),
("🇨🇭", "Switzerland Flag"),
("🇸🇾", "Syria Flag"),
("🇸🇹", "São Tomé & Príncipe Flag"),
("🇹🇼", "Taiwan Flag"),
("🇹🇯", "Tajikistan Flag"),
("🇹🇿", "Tanzania Flag"),
("🇹🇭", "Thailand Flag"),
("🇹🇱", "Timor-Leste Flag"),
("🇹🇬", "Togo Flag"),
("🇹🇰", "Tokelau Flag"),
("🇹🇴", "Tonga Flag"),
("🇹🇹", "Trinidad & Tobago Flag"),
("🇹🇦", "Tristan da Cunha Flag"),
("🇹🇳", "Tunisia Flag"),
("🇹🇷", "Turkey Flag"),
("🇹🇲", "Turkmenistan Flag"),
("🇹🇨", "Turks & Caicos Islands Flag"),
("🇹🇻", "Tuvalu Flag"),
("🇺🇬", "Uganda Flag"),
("🇺🇦", "Ukraine Flag"),
("🇦🇪", "United Arab Emirates Flag"),
("🇬🇧", "United Kingdom Flag"),
("🏴󠁧󠁢󠁥󠁮󠁧󠁿", "England Flag"),
("🏴󠁧󠁢󠁳󠁣󠁴󠁿", "Scotland Flag"),
("🏴󠁧󠁢󠁷󠁬󠁳󠁿", "Wales Flag"),
("🇺🇳", "United Nations Flag"),
("🇺🇸", "United States Flag"),
("🇺🇾", "Uruguay Flag"),
("🇺🇿", "Uzbekistan Flag"),
("🇻🇺", "Vanuatu Flag"),
("🇻🇦", "Vatican City Flag"),
("🇻🇪", "Venezuela Flag"),
("🇻🇳", "Vietnam Flag"),
("🇻🇮", "U.S. Virgin Islands Flag"),
("🇼🇫", "Wallis & Futuna Flag"),
("🇪🇭", "Western Sahara Flag"),
("🇾🇪", "Yemen Flag"),
("🇿🇲", "Zambia Flag"),
("🇿🇼", "Zimbabwe Flag")
]